site_name: Interpretabilidade ML com SHAP
repo_url: https://github.com/douglasaturnino/ml-shap
repo_name: douglasaturnino/ml-shap

theme:
  name: material
  features:
    - navigation.top

nav:
  - Introdução: index.md
  - Dicionario de dados: dictionary.md
  - Modo de uso: utilizacao.md
  - API: process.md
  - APP: app.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkdocstrings

