model:
  ml_path: /model/model.pkl
  threshold: 0.75
  shap_path: /model/explainer_xgb.pkl

model_columns:
  x_columns:
  - dependentes
  - estado_civil
  - idade
  - cheque_sem_fundo
  - valor_emprestimo
  target: pago

api:
  host: '0.0.0.0'
  porta: 8001
  path_predict: '/predict'
  path_predict_file: '/predict_file'